### ISSUE TITLE
Can you explain in more detail, how to install and use this on OS X?

### ISSUE THREAD

**Issue by oliveratgithub** [rbaron/dict.cc.py#5]
Hi @rbaron 
I tried to get this to run on OS X, but without any success ("pip" not available). Can you explain in more detail, what is required and how to setup the application to run this on OS X (I think it's most likely very similiar to Linux anyway)?

Additionally, I feel like one needs to obtain some file(s) from dict.cc - like the translation database(s) - additionally to the application itself. Can this be? If yes, where and which files do I need?

Thanks & best regards,
Oliver

**Comment by rbaron** [comment]
Hi @oliveratgithub, 

`pip` is a package manager for python. I'm not an OSX user, but I have googled and it seems you can install it with `sudo easy_install pip` (as seen [here](http://stackoverflow.com/questions/17271319/installing-pip-on-mac-os-x)).

The way `dict.cc.py` works is by sending http://dict.cc the words to be translated and parsing the results, very much like your brower would do. Therefore you don't actually need to download a dictionary database, since the translations are done on the fly, via HTTP requests.

Does that clear it up?

**Comment by oliveratgithub** [comment]
aah I see... thanks, yes that helped! :)
